#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <api_demo_icons.h>

#include <gui/scene_manager.h>
#include <gui/view_dispatcher.h>
#include <gui/modules/text_box.h>
#include <gui/modules/submenu.h>

typedef enum {
    Scene_MainMenu,
    Scene_TextBoxOne,
    Scene_count
} Scene;
typedef enum {
    Views_Submenu,
    Views_TextBox
} Views;

typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Submenu* submenu;
    TextBox* textbox;
} ApiDemo;
void api_demo_submenu_callback(void* context, uint32_t index) {
    ApiDemo* app = context;
    scene_manager_next_scene(app->scene_manager, index);
}
void api_demo_scene_on_enter_MainMenu(void* context) {
    ApiDemo* app = context;
    submenu_reset(app->submenu);
    submenu_add_item(app->submenu, "text1", Scene_TextBoxOne, api_demo_submenu_callback, app);
}
bool api_demo_scene_on_event_MainMenu(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}
void api_demo_scene_on_exit_MainMenu(void* context) {
    ApiDemo* app = context;
    submenu_reset(app->submenu);
}

void api_demo_scene_on_enter_TextBoxOne(void* context) {
    ApiDemo* app = context;
    text_box_reset(app->textbox);
    text_box_set_text(
        app->textbox,
        "this is my text, it is very nice text, this is a very long line \nthis is the next line");
}
bool api_demo_scene_on_event_TextBoxOne(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}
void api_demo_scene_on_exit_TextBoxOne(void* context) {
    ApiDemo* app = context;
    text_box_reset(app->textbox);
}

//collection of all on enter, event, and exit methods
//all on enter
void (*const api_demo_scene_on_enter_handlers[])(void*) = {
    api_demo_scene_on_enter_MainMenu,
    api_demo_scene_on_enter_TextBoxOne};
//all on event
bool (*const api_demo_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    api_demo_scene_on_event_MainMenu,
    api_demo_scene_on_event_TextBoxOne};
//all on exit
void (*const api_demo_scene_on_exit_handlers[])(void*) = {
    api_demo_scene_on_exit_MainMenu,
    api_demo_scene_on_exit_TextBoxOne};
//combination
const SceneManagerHandlers api_demo_scene_event_handlers = {
    .on_enter_handlers = api_demo_scene_on_enter_handlers,
    .on_event_handlers = api_demo_scene_on_event_handlers,
    .on_exit_handlers = api_demo_scene_on_exit_handlers,
    .scene_num = Scene_count};

void api_demo_scene_manager_init(ApiDemo* app) {
    app->scene_manager = scene_manager_alloc(&api_demo_scene_event_handlers, app);
}
bool api_demo_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    ApiDemo* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}
bool api_demo_scene_manager_navigation_event_callback(void* context) {
    ApiDemo* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}
void api_demo_view_dispatcher_init(ApiDemo* app) {
    app->submenu = submenu_alloc();
    app->textbox = text_box_alloc();

    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, api_demo_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, api_demo_scene_manager_navigation_event_callback);

    view_dispatcher_add_view(app->view_dispatcher, Views_Submenu, submenu_get_view(app->submenu));
    view_dispatcher_add_view(app->view_dispatcher, Views_TextBox, text_box_get_view(app->textbox));
}
ApiDemo* api_demo_init() {
    ApiDemo* app = malloc(sizeof(ApiDemo));
    api_demo_scene_manager_init(app);
    api_demo_view_dispatcher_init(app);
    return app;
}
void api_demo_free(ApiDemo* app) {
    scene_manager_free(app->scene_manager);

    view_dispatcher_remove_view(app->view_dispatcher, Views_Submenu);
    view_dispatcher_remove_view(app->view_dispatcher, Views_TextBox);
    view_dispatcher_free(app->view_dispatcher);

    submenu_free(app->submenu);
    text_box_free(app->textbox);
    free(app);
}
int32_t api_demo_app() {
    ApiDemo* app = api_demo_init();
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, Scene_MainMenu);

    view_dispatcher_run(app->view_dispatcher);

    api_demo_free(app);
    return 0;
}
